name: unlist

on:
  workflow_dispatch:

jobs:
  unlist:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v5
        
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: Lo_Wang

      - name: Unlist packages
        shell: pwsh
        run: pwsh ./unlist.ps1 -key ${{steps.login.outputs.NUGET_API_KEY}}
